/**
 * Shared logic for the two Scaffolded Learning modules — Take Test Mastery and
 * Review Materials. Used by `student/remediation.jsx` and the class page's
 * Topics tab, which present the same two things in different places.
 *
 * Lives under `routes/student/` rather than `src/lib/` on purpose: `src/lib/**`
 * belongs to the Data lane (see OWNERSHIP.md), and this is student-page logic.
 *
 * MASTERY IS DERIVED, NEVER STORED. A topic's mastery is the student's best
 * attempt percentage across the quizzes linked to that topic. That is the whole
 * mechanism behind "take the remediation quiz and your mastery updates" — a new
 * attempt changes what this calculation returns, so nothing has to be written
 * back. It also means mastery can never drift out of sync with the attempts it
 * claims to summarise.
 *
 * The best-of rule and the thresholds mirror
 * `teacher/classes/$classId/scaffolds.jsx` exactly, so a student and their
 * teacher never read different numbers for the same topic. Change them together.
 */
import { green, goldDeep, red, faint } from '@/theme'

/** An attempt at or above this counts as mastered for that student. */
export const PASS = 75
const NEEDS_BELOW = 60
const DEVELOPING_BELOW = 80

export function quizTotalPoints(quiz) {
  const summed = (quiz?.questions ?? []).reduce((s, q) => s + (Number(q.points) || 0), 0)
  // Remediation quizzes generated by AI sometimes carry total_possible without
  // per-question points; fall back rather than dividing by zero and hiding them.
  return summed || Number(quiz?.total_possible) || 0
}

export function bucketOf(pct) {
  if (pct == null) return 'none'
  if (pct < NEEDS_BELOW) return 'needs'
  if (pct < DEVELOPING_BELOW) return 'developing'
  return 'mastered'
}

export const BUCKETS = {
  none: { label: 'Not attempted', fg: faint, bg: 'rgba(14,42,92,0.05)', border: 'rgba(14,42,92,0.12)' },
  needs: { label: 'Needs work', fg: red, bg: 'rgba(192,57,43,0.07)', border: 'rgba(192,57,43,0.30)' },
  developing: { label: 'Developing', fg: goldDeep, bg: 'rgba(245,197,24,0.16)', border: 'rgba(245,197,24,0.5)' },
  mastered: { label: 'Mastered', fg: green, bg: 'rgba(31,138,91,0.10)', border: 'rgba(31,138,91,0.38)' },
}

/** Quizzes wired to a syllabus topic. `topic_id` is the only link that exists. */
export function quizzesForTopic(topicId, quizzes = []) {
  return topicId ? quizzes.filter((q) => q.topic_id === topicId) : []
}

/**
 * The student's own mastery of one topic.
 * Returns pct = null when they have no scored attempt yet — which is different
 * from 0%, and is shown differently.
 */
export function topicMastery(topicId, quizzes = [], attemptsByQuiz = {}) {
  return masteryOf(quizzesForTopic(topicId, quizzes), attemptsByQuiz)
}

/**
 * The quizzes a remediation offers as its mastery test: every quiz linked to
 * its topic, plus the one the teacher attached to the plan itself —
 * `recommended_quiz_id`, which is what features/classes/remediation.js writes
 * onto each student's copy. That quiz may carry a different topic_id, or none
 * (the plan's topic can be null too), and the topic-only lookup never showed it.
 */
export function remediationQuizzes(r, quizzes = []) {
  const linked = quizzesForTopic(r?.topic_id, quizzes)
  const pinned = r?.recommended_quiz_id ? quizzes.find((q) => q.id === r.recommended_quiz_id) : null
  if (pinned && !linked.some((q) => q.id === pinned.id)) return [pinned, ...linked]
  return linked
}

/** Mastery over an explicit set of quizzes. Best scored attempt wins. */
export function masteryOf(linked = [], attemptsByQuiz = {}) {
  let best = null
  let attempts = 0

  for (const q of linked) {
    const total = quizTotalPoints(q)
    if (!total) continue
    for (const a of attemptsByQuiz[q.id] ?? []) {
      if (a.total_score == null) continue // still being marked, or still open
      attempts += 1
      const pct = (a.total_score / total) * 100
      if (best == null || pct > best) best = pct
    }
  }

  const pct = best == null ? null : Math.round(best)
  return { pct, attempts, bucket: bucketOf(pct), quizzes: linked }
}

/**
 * A quiz reaches a student if it is assigned to everyone ('all', or a legacy
 * undefined) or names them. Shared so the class page and the remediation page
 * cannot disagree about which quizzes a student is allowed to see. Since
 * 2026-09-13 the one definition is lib/deliverables.js, which the student's
 * dashboard hook also reads; re-exported here so the class and remediation
 * pages keep their import.
 */
export { assignedToStudent } from '@/lib/deliverables'

/** The teacher's scaffolds page titles these `Remediation · <topic>`. */
export function isRemediationQuiz(quiz) {
  return typeof quiz?.title === 'string' && quiz.title.startsWith('Remediation ·')
}

/**
 * Walk a syllabus for one topic, and hand back its module for context.
 *
 * The positions are 1-based and count only what the student can see: the
 * syllabus reaching this code has already had unpublished modules filtered
 * out (`loadSyllabus`), so "Module 2" here is the second module on the
 * student's Modules tab, not the second one the teacher typed.
 */
export function findTopic(syllabus, topicId) {
  if (!syllabus || !topicId) return null
  const modules = syllabus.modules ?? []
  for (let mi = 0; mi < modules.length; mi++) {
    const m = modules[mi]
    const topics = m.topics ?? []
    for (let ti = 0; ti < topics.length; ti++) {
      const t = topics[ti]
      if (t.id === topicId) return { topic: t, module: m, moduleNo: mi + 1, topicNo: ti + 1 }
    }
  }
  return null
}

/**
 * Where a scaffolded topic sits in the teacher's modules, in the words the
 * Modules tab uses: a module, and a sub-module inside it (the tab calls a
 * `topic` a sub-module; there is no separate lecture level in a syllabus).
 *
 * Returns null when the topic is not in the published modules — the caller
 * decides what to say, because "not linked" and "no longer published" are
 * different situations and both already have wording on the card.
 */
export function topicLocation(syllabus, topicId) {
  const found = findTopic(syllabus, topicId)
  if (!found) return null
  return {
    ...found,
    moduleLabel: `Module ${found.moduleNo}`,
    moduleTitle: found.module.title || `Module ${found.moduleNo}`,
    topicLabel: `Sub-module ${found.topicNo}`,
    topicTitle: found.topic.title || `Sub-module ${found.topicNo}`,
    resourceCount: (found.topic.resources ?? []).length,
  }
}

/** The DOM id the Modules tab gives one sub-module, so a link can land on it. */
export function topicAnchorId(topicId) {
  return `topic-${topicId}`
}

/**
 * A link that opens the class page on the Modules tab with one sub-module in
 * view. The class page reads both query parameters (`tab`, `topic`); the
 * anchor alone would not do, because the tab is not mounted until chosen.
 */
export function topicHref(classId, topicId) {
  const q = new URLSearchParams({ tab: 'topics' })
  if (topicId) q.set('topic', topicId)
  return `/student/classes/${classId}?${q.toString()}`
}

/**
 * Whether a learning resource can actually be opened.
 *
 * A `file` resource carries the download URL the syllabus page got back from
 * Storage (live since 2026-09-12, on Blaze). One saved before that date, or
 * whose upload failed, has no URL and no object behind it, so the href would
 * be dead. Saying why is more use to a student than a link that fails, and it
 * stops them assuming the material is missing from the course.
 */
export function resourceState(res) {
  switch (res?.resource_type) {
    case 'file':
      return res.url
        ? { available: true }
        : { available: false, reason: 'This file was never uploaded, so it cannot be opened here. Ask your teacher for a copy.' }
    case 'link':
      return res.url
        ? { available: true }
        : { available: false, reason: 'No address was saved for this link.' }
    case 'rich_text':
      return res.content_markdown?.trim()
        ? { available: true }
        : { available: false, reason: 'This study note has not been written yet.' }
    default:
      return { available: false, reason: 'This resource type is not supported yet.' }
  }
}

export const RESOURCE_META = {
  file: { icon: '📄', label: 'File' },
  link: { icon: '🔗', label: 'Link' },
  rich_text: { icon: '✍️', label: 'Study note' },
}
