/**
 * Shared logic for the two Scaffolded Learning modules — Take Test Mastery and
 * Review Materials. Used by `student/remediation.jsx` and the class page's
 * Topics tab, which present the same two things in different places.
 *
 * Lives under `routes/student/` rather than `src/lib/` on purpose: `src/lib/**`
 * belongs to the Data lane (see OWNERSHIP.md), and this is student-page logic.
 *
 * MASTERY IS DERIVED, NEVER STORED. A topic's mastery is the student's best
 * attempt percentage across the quizzes linked to that topic. That is the whole
 * mechanism behind "take the remediation quiz and your mastery updates" — a new
 * attempt changes what this calculation returns, so nothing has to be written
 * back. It also means mastery can never drift out of sync with the attempts it
 * claims to summarise.
 *
 * The best-of rule and the thresholds mirror
 * `teacher/classes/$classId/scaffolds.jsx` exactly, so a student and their
 * teacher never read different numbers for the same topic. Change them together.
 */
import { green, goldDeep, red, faint } from '@/theme'

/** An attempt at or above this counts as mastered for that student. */
export const PASS = 75
const NEEDS_BELOW = 60
const DEVELOPING_BELOW = 80

export function quizTotalPoints(quiz) {
  const summed = (quiz?.questions ?? []).reduce((s, q) => s + (Number(q.points) || 0), 0)
  // Remediation quizzes generated by AI sometimes carry total_possible without
  // per-question points; fall back rather than dividing by zero and hiding them.
  return summed || Number(quiz?.total_possible) || 0
}

export function bucketOf(pct) {
  if (pct == null) return 'none'
  if (pct < NEEDS_BELOW) return 'needs'
  if (pct < DEVELOPING_BELOW) return 'developing'
  return 'mastered'
}

export const BUCKETS = {
  none: { label: 'Not attempted', fg: faint, bg: 'rgba(14,42,92,0.05)', border: 'rgba(14,42,92,0.12)' },
  needs: { label: 'Needs work', fg: red, bg: 'rgba(192,57,43,0.07)', border: 'rgba(192,57,43,0.30)' },
  developing: { label: 'Developing', fg: goldDeep, bg: 'rgba(245,197,24,0.16)', border: 'rgba(245,197,24,0.5)' },
  mastered: { label: 'Mastered', fg: green, bg: 'rgba(31,138,91,0.10)', border: 'rgba(31,138,91,0.38)' },
}

/** Quizzes wired to a syllabus topic. `topic_id` is the only link that exists. */
export function quizzesForTopic(topicId, quizzes = []) {
  return topicId ? quizzes.filter((q) => q.topic_id === topicId) : []
}

/**
 * The student's own mastery of one topic.
 * Returns pct = null when they have no scored attempt yet — which is different
 * from 0%, and is shown differently.
 */
export function topicMastery(topicId, quizzes = [], attemptsByQuiz = {}) {
  const linked = quizzesForTopic(topicId, quizzes)
  let best = null
  let attempts = 0

  for (const q of linked) {
    const total = quizTotalPoints(q)
    if (!total) continue
    for (const a of attemptsByQuiz[q.id] ?? []) {
      if (a.total_score == null) continue // still being marked
      attempts += 1
      const pct = (a.total_score / total) * 100
      if (best == null || pct > best) best = pct
    }
  }

  const pct = best == null ? null : Math.round(best)
  return { pct, attempts, bucket: bucketOf(pct), quizzes: linked }
}

/**
 * A quiz reaches a student if it is assigned to everyone ('all', or a legacy
 * undefined) or names them. Shared so the class page and the remediation page
 * cannot disagree about which quizzes a student is allowed to see.
 */
export function assignedToStudent(quiz, studentId) {
  const a = quiz?.assigned_to
  return !a || a === 'all' || (Array.isArray(a) && a.includes(studentId))
}

/** The teacher's scaffolds page titles these `Remediation · <topic>`. */
export function isRemediationQuiz(quiz) {
  return typeof quiz?.title === 'string' && quiz.title.startsWith('Remediation ·')
}

/** Walk a syllabus for one topic, and hand back its module for context. */
export function findTopic(syllabus, topicId) {
  if (!syllabus || !topicId) return null
  for (const m of syllabus.modules ?? []) {
    for (const t of m.topics ?? []) {
      if (t.id === topicId) return { topic: t, module: m }
    }
  }
  return null
}

/**
 * Whether a learning resource can actually be opened.
 *
 * Firebase Storage is NOT enabled on this project, so a `file` resource has no
 * object behind it — the upload that would have produced a download URL never
 * succeeded. Any href we render for one is dead. Saying why is more use to a
 * student than a link that fails, and it stops them assuming the material is
 * missing from the course rather than merely unhosted.
 */
export function resourceState(res) {
  switch (res?.resource_type) {
    case 'file':
      return {
        available: false,
        reason: 'File downloads are switched off for this school, so this one cannot be opened here. Ask your teacher for a copy.',
      }
    case 'link':
      return res.url
        ? { available: true }
        : { available: false, reason: 'No address was saved for this link.' }
    case 'rich_text':
      return res.content_markdown?.trim()
        ? { available: true }
        : { available: false, reason: 'This study note has not been written yet.' }
    default:
      return { available: false, reason: 'This resource type is not supported yet.' }
  }
}

export const RESOURCE_META = {
  file: { icon: '📄', label: 'File' },
  link: { icon: '🔗', label: 'Link' },
  rich_text: { icon: '✍️', label: 'Study note' },
}
